package casa.pallavolo.utils;

public class Constants {
    public final static String TITOLO_PDF = "SETTORE DI ATTIVITÀ PALLAVOLO UISP LAZIO SUD EST";
    public final static String PRIMO_SOTTOTITOLO = "LISTA PARTECIPANTI ALLA GARA";
    public final static String SECONDO_SOTTOTITOLO = "DENOMINAZIONE DELLA SQUADRA";
    public final static String TITOLO_DEFIBRILLATORE = "DA COMPILARE DA PARTE DELLA SOLA SQUADRA OSPITANTE";
    public final static String SOTTOTITOLO_DEFIBRILLATORE = "AUTOCERTIFICAZIONE DELL'ADDETTO ALL'UTILIZZO DEL DEFIBRILLATORE (ART. 45 E 46 DPR 28 DICEMBRE 2000 N. 445)";
    public final static String TESTO_DICHIARAZIONE_DEFIBRILLATORE = "CONSAPEVOLE DELLE SANZIONI PENALI NEL CASO DI DICHIARAZIONI MENDACI, DI FORMAZIONE O USO DI ATTI FALSI (ARTICOLO 76, DPR N. 445/2000) DICHIARA SOTTO LA PROPRIA RESPONSABILITÀ CHE NELL’IMPIANTO È PRESENTE IL DEFIBRILLATORE, DI ESSERE PERSONA FORMATA ALL’UTILIZZO DEL DAE E DI ESSERE IN POSSESSO DEI REQUISITI PREVISTI DALLE NORMATIVE VIGENTI IN MATERIA DI DEFIBRILLATORI E LORO UTILIZZO.";
}
